# Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
include $(LITEOSTOPDIR)/../../drivers/adapter/khdf/liteos/lite.mk

MODULE_NAME := hdf_test_config
LOCAL_HCS_ROOT := $(shell pwd)

LOCAL_PLATFORM_HCS_SRC := hdf_test.hcs

include $(HDF_DRIVER)
