#! /bin/sh

echo "ohos_service_start"
mknod /dev/hilog c 245 1
chmod 666 /dev/hilog
mknod /dev/hwlog_exception   c 241 1
chmod 666 /dev/hwlog_exception
cd /ko
./load_hi3403v100_ohos -i -display drm
chmod 666 /dev/mmz_userdev
chmod 777 /dev/i2c-0
chmod 666 /dev/sys
chmod 777 /dev/mem
/etc/init.d/gpio &
