#!/bin/sh
# Copyright (c) 2025 HiSilicon (Shanghai) Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir /config
mount -t configfs none /config

mkdir /config/usb_gadget/g1 -m 0770
chown shell:shell /config/usb_gadget/g1

echo "0x2207" > /config/usb_gadget/g1/idVendor
echo "0x5000" > /config/usb_gadget/g1/idProduct
echo "0x0223" > /config/usb_gadget/g1/bcdDevice
echo "0x0200" > /config/usb_gadget/g1/bcdUSB

mkdir /config/usb_gadget/g1/strings/0x409 -m 0770
cp /sys/block/mmcblk0/device/cid /config/usb_gadget/g1/strings/0x409/serialnumber
echo "HISILICON" > /config/usb_gadget/g1/strings/0x409/manufacturer 
echo "HDC Device" > /config/usb_gadget/g1/strings/0x409/product

echo "0x1" > /config/usb_gadget/g1/os_desc/b_vendor_code  
echo "MSFT100" > /config/usb_gadget/g1/os_desc/qw_sign 
echo "1" > /config/usb_gadget/g1/os_desc/use

mkdir /config/usb_gadget/g1/configs/c.1 -m 0770
chown shell:shell /config/usb_gadget/g1/configs/c.1
mkdir /config/usb_gadget/g1/configs/c.1/strings/0x409 -m 0770
chown shell:shell /config/usb_gadget/g1/configs/c.1/strings/0x409 
echo "500" > /config/usb_gadget/g1/configs/c.1/MaxPower 
echo "hdc" > /config/usb_gadget/g1/configs/c.1/strings/0x409/configuration
ln -s /config/usb_gadget/g1/configs/c.1 /config/usb_gadget/g1/os_desc/c.1 

mkdir -p /config/usb_gadget/g1/functions/ffs.hdc
ln -s /config/usb_gadget/g1/functions/ffs.hdc /config/usb_gadget/g1/configs/c.1

mkdir /dev/usb-ffs -m 0770 
chown shell:shell /dev/usb-ffs 
mkdir -p /dev/usb-ffs/hdc -m 0770
chown shell:shell /dev/usb-ffs/hdc 
mount -t functionfs hdc /dev/usb-ffs/hdc -o uid=2000,gid=2000
